app/main/forms.py
"""
Module described forms
"""
from flask_wtf import FlaskForm
from wtforms import StringField, RadioField, SubmitField, StringField
from wtforms.validators import DataRequired, ValidationError
from datetime import datetime
import re


class EditCollection(FlaskForm):
    choice = ["user_email", "user_phone", "order_date", "comment"]
    name = StringField("name", validators=[DataRequired()])
    field1_name = RadioField("field1_type", choices=choice, validate_choice=False)
    field1_value = StringField("field1_value", validators=[DataRequired()])
    field2_name = RadioField("field2_type", choices=choice, validate_choice=False)
    field2_value = StringField("field2_value", validators=[DataRequired()])
    submit = SubmitField("Submit")

    def validate_field1_value(self, field):
        if self.field1_name.data == "user_email":
            pattern = "^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$"
            if re.match(pattern, field.data) is None:
                raise ValidationError("Wrong email")
        elif self.field1_name.data == "user_phone":
            pattern = "^\+7 \d{3} \d{3} \d{2} \d{2}$"
            if re.match(pattern, field.data) is None:
                raise ValidationError("Wrong phone")
        elif self.field1_name.data == "order_date":
            pattern1 = "^\d{2}\.\d{2}\.\d{4}$"
            pattern2 = "^\d{4}-\d{2}-\d{2}$"
            if re.match(pattern1, field.data) is None or re.match(pattern2, field.data) is None:
                raise ValidationError("Wrong date")
            else:
                try:
                    if field.data[2] == ".":
                        datetime.strptime(field.data, "%d.%m.%Y")
                    else:
                        datetime.strptime(field.data, "%Y-%m-%d")
                except:
                    raise ValidationError("Wrong date")

    def validate_field2_value(self, field):
        if self.field2_name.data == "email":
            pattern = "^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$"
            if re.match(pattern, field.data) is None:
                raise ValidationError("Wrong email")
        elif self.field2_name.data == "phone":
            pattern = "^\+7 \d{3} \d{3} \d{2} \d{2}$"
            if re.match(pattern, field.data) is None:
                raise ValidationError("Wrong phone")
        elif self.field2_name.data == "date":
            pattern1 = "^\d{2}\.\d{2}\.\d{4}$"
            pattern2 = "^\d{4}-\d{2}-\d{2}$"
            if re.match(pattern1, field.data) is None or re.match(pattern2, field.data) is None:
                raise ValidationError("Wrong date")
            else:
                try:
                    if field.data[2] == ".":
                        datetime.strptime(field.data, "%d.%m.%Y")
                    else:
                        datetime.strptime(field.data, "%Y-%m-%d")
                except:
                    raise ValidationError("Wrong date")


class TestForm(FlaskForm):
    # choice = ["user_email", "user_phone", "order_date", "comment"]
    # field1_name = RadioField("field1_type", choices=choice, validate_choice=False)
    field1_name = StringField("field1_type", validators=[DataRequired()])
    field1_value = StringField("field1_value", validators=[DataRequired()])
    # field2_name = RadioField("field2_type", choices=choice, validate_choice=False)
    field2_name = StringField("field2_type", validators=[DataRequired()])
    field2_value = StringField("field2_value", validators=[DataRequired()])
    submit = SubmitField("Submit")


class AutoForm(FlaskForm):
    submit =SubmitField("Populate")

app/__init__.py
from flask import Flask
from config import DevelopmentConfig, ProductionConfig, TestingConfig
from pymongo import MongoClient

profiles = {
    "development": DevelopmentConfig(),
    "production": ProductionConfig(),
    "testing": TestingConfig()
}

# client = MongoClient()


def create_app(profile) -> Flask:
    """
    Create app and loading config
    :param profile: dev prod or test profile
    :return: app flask
    """
    app = Flask(__name__)
    app.config.from_object(profiles[profile])
    client = MongoClient(app.config["MONGO_URI"])
    app.db = client["app"]

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.api import bp as api_bp
    app.register_blueprint(api_bp, url_prefix="/api")

    return app

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import routes

app/api/routes.py
# from app import db
from flask import request, jsonify, current_app, make_response
from app.api import bp
import re
from datetime import datetime


@bp.route("/get_form", methods=["GET", "POST"])
def get_form():
    if request.method == "POST":
        print(request)
        f1 = [request.form["field1_name"], request.form["field1_value"]]
        f2 = [request.form["field2_name"], request.form["field2_value"]]
        for f in [f1, f2]:
            if f[0] == "user_email":
                pattern = "^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$"
                if re.match(pattern, f[1]) is None:
                    return make_response(jsonify([f1, f2], 200))
            elif f[0] == "user_phone":
                pattern = "^\+7 \d{3} \d{3} \d{2} \d{2}$"
                if re.match(pattern, f[1]) is None:
                    return make_response(jsonify([f1, f2], 200))
            elif f[0] == "order_date":
                pattern1 = "^\d{2}\.\d{2}\.\d{4}$"
                pattern2 = "^\d{4}-\d{2}-\d{2}$"
                if re.match(pattern1, f[1]) is None or re.match(pattern2, f[1]) is None:
                    try:
                        if f[1][2] == ".":
                            datetime.strptime(f[1], "%d.%m.%Y")
                        else:
                            datetime.strptime(f[1], "%Y-%m-%d")
                    except:
                        return make_response(jsonify([f1, f2], 200))
        data = list(current_app.db.test_coll.find({f1[0]: {"$exists": 1}, f2[0]: {"$exists": 1}}, {"_id": 0, "name": 1}))
        if not data:
            data = [f1, f2]
        return make_response(jsonify(data, 200))
    else:
        return make_response(jsonify("{Method: get}", 200))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes, forms

app/main/routes.py
from app.main import bp
from flask import render_template, url_for, current_app, request, flash, redirect
from .forms import EditCollection, TestForm, AutoForm
from app.mongo import populate


@bp.route("/", methods=["GET", "POST"])
def index():
    form = AutoForm()
    if form.validate_on_submit():
        populate()
    return render_template("index.html", form=form)


@bp.route("/edit", methods=["GET", "POST"])
def edit():
    form = EditCollection()
    if form.validate_on_submit():
        data = {"name": form.name.data,
                form.field1_name.data: form.field1_value.data,
                form.field2_name.data: form.field2_value.data}
        current_app.db.test_coll.insert_one(data)
        flash("Data updated")
        # return redirect(url_for("main.view"))
    return render_template("edit.html", form=form)


@bp.route("/view/<string:coll_name>")
@bp.route("/view")
def view(coll_name: str = ""):
    if coll_name == "":
        my_coll = current_app.db.list_collection_names()
    else:
        my_coll = current_app.db.test_coll.find()
    return render_template("view.html", coll=my_coll)


@bp.route("/test")
def test():
    form = TestForm()
    return render_template("test.html", form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to ecom</title>
</head>
<body>
    <hr>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            <hr>
        {% endif %}
    {% endwith %}
    {% block menu %}
    <ul>
        <li><a href="{{ url_for('main.index')}}">Main</a></li>
        <li><a href="{{ url_for('main.edit')}}">Collection Edit</a></li>
        <li><a href="{{ url_for('main.view')}}">Collection View</a></li>
        <li><a href="{{ url_for('main.test')}}">Test</a></li>
    </ul>
    {% endblock %}
    {% block content %}

    {% endblock %}
</body>
</html>

app/templates/edit.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}

    Edit collection

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}
<hr>
        <a href="{{ url_for('main.index')}}">Main</a><br>
        <a href="{{ url_for('main.edit')}}">Collection Edit</a><br>
        <a href="{{ url_for('main.view')}}">Collection View</a><br>
        <a href="{{ url_for('main.test')}}">Test</a><br>
        <form action="", method="POST">
                {{ form.hidden_tag() }}
                <p>{{ form.submit() }}</p>
        </form>
{% endblock %}

app/templates/test.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}
    <hr>
    Test collection
    <hr>
    {% if form %}
        <form action="/api/get_form" method="POST">
            {{ form.hidden_tag() }}
            <p>
                {{ form.field1_name.label }}<br>
                {{ form.field1_name(cols=32, rows=4)}}<br>
                {{ form.field1_value.label }}<br>
                {% for error in form.field1_value.errors %}
                    <span color="red">[{{ error }}]</span>
                {% endfor %}<br>
                {{ form.field1_value(cols=32, rows=4)}}<br>
                {{ form.field2_name.label }}<br>
                {{ form.field2_name(cols=32, rows=4)}}<br>
                {{ form.field2_value.label }}<br>
                {% for error in form.field2_value.errors %}
                    <span color="red">[{{ error }}]</span>
                {% endfor %}<br>
                {{ form.field2_value(cols=32, rows=4)}}<br>

            </p>
            <p>{{ form.submit() }}</p>
        </form>
    {% endif %}
{% endblock %}

app/templates/view.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}

    View collection
    <hr>
    {% for el in coll %}
        {% if el["name"] %}
            <div>{{el}}</div>
        {% else %}
            <div><a href="{{url_for('main.view', coll_name = el)}}">{{el}}</a></div>
        {% endif %}

    {% endfor %}

{% endblock %}